<?php

return [
    "Abyssal Wraith", "Aether Beast", "Arcane Serpent", "Astral Horror", "Banshee Phantom",
    "Basilisk King", "Blaze Titan", "Bloodfang Wolf", "Boneclaw Revenant", "Crimson Drake",
    "Darkfire Demon", "Deathshade Specter", "Dreadhorn Minotaur", "Ebon Wyrm", "Emberclaw Chimera",
    "Frostbite Yeti", "Gloomstalker", "Grimshadow Fiend", "Hellspawn Brute", "Infernal Golem",
    "Ironhide Ogre", "Lunar Leviathan", "Molten Behemoth", "Nightshade Basilisk", "Obsidian Colossus",
    "Phantom Warlock", "Ravenous Hydra", "Shadowfang Panther", "Soulreaper Lich", "Thunderclaw Griffin",
    "Venomspine Scorpion", "Voidwalker", "Wailing Banshee", "Wraithlord", "Zephyr Dragon",
    "Abyssal Crawler", "Aetherial Shade", "Ancient Behemoth", "Ashen Phoenix", "Blighted Treant",
    "Bloodthorn Vine", "Brimstone Elemental", "Cinderhorn Ram", "Corrupted Titan", "Cursed Wight",
    "Darksoul Revenant", "Deathclaw Raptor", "Doombringer", "Dreadmaw Crocodile", "Eldritch Abomination",
    "Emberfang Wolf", "Frostfang Bear", "Ghastly Specter", "Gorehorn Bull", "Grimclaw Tiger",
    "Hellfire Imp", "Ironjaw Boar", "Lurking Horror", "Mireclaw Crab", "Netherfiend",
    "Nightmare Stalker", "Oblivion Wraith", "Plaguebearer", "Ravenshadow Raven", "Rotfiend Zombie",
    "Scorchwing Drake", "Shadowclaw Panther", "Soulflame Wisp", "Thunderhoof Stag", "Venomfang Spider",
    "Vileblood Bat", "Wailing Specter", "Wightlord", "Zephyr Hawk", "Abyssal Leviathan",
    "Aetherial Phantom", "Ancient Colossus", "Ashen Drake", "Blighted Ent", "Bloodthorn Bramble",
    "Brimstone Golem", "Cinderclaw Lynx", "Corrupted Behemoth", "Cursed Specter", "Darksoul Wight",
    "Deathclaw Wyvern", "Doomfang Wolf", "Dreadmaw Alligator", "Eldritch Horror", "Emberfang Direwolf",
    "Frostfang Polar Bear", "Ghastly Wraith", "Gorehorn Bison", "Grimclaw Sabertooth", "Hellfire Demon",
    "Ironjaw Warthog", "Lurking Abomination", "Mireclaw Lobster", "Netherfiend Imp", "Nightmare Phantom",
    "Oblivion Specter", "Plaguefiend", "Ravenshadow Crow", "Rotfiend Ghoul", "Scorchwing Wyvern",
    "Shadowclaw Jaguar", "Soulflame Ghost", "Thunderhoof Elk", "Venomfang Tarantula", "Vileblood Vampire",
    "Wailing Wraith", "Wight Revenant", "Zephyr Falcon", "Abyssal Kraken", "Aetherial Specter",
    "Ancient Titan", "Ashen Wyvern", "Blighted Dryad", "Bloodthorn Thornback", "Brimstone Titan",
    "Cinderclaw Cougar", "Corrupted Colossus", "Cursed Wraith", "Darksoul Specter", "Deathclaw Drake",
    "Doomfang Direwolf", "Dreadmaw Croc", "Eldritch Specter", "Emberfang Wolf", "Frostfang Grizzly",
    "Ghastly Phantom", "Gorehorn Buffalo", "Grimclaw Tiger", "Hellfire Fiend", "Ironjaw Boar",
    "Lurking Specter", "Mireclaw Crayfish", "Netherfiend Demon", "Nightmare Wraith", "Oblivion Phantom",
    "Plaguefiend Zombie", "Ravenshadow Raven", "Rotfiend Skeleton", "Scorchwing Drake", "Shadowclaw Panther",
    "Soulflame Wisp", "Thunderhoof Moose", "Venomfang Widow", "Vileblood Bat", "Wailing Specter",
    "Wightlord", "Zephyr Hawk", "Abyssal Leviathan", "Aetherial Phantom", "Ancient Colossus",
    "Ashen Drake", "Blighted Ent", "Bloodthorn Bramble", "Brimstone Golem", "Cinderclaw Lynx",
    "Corrupted Behemoth", "Cursed Specter", "Darksoul Wight", "Deathclaw Wyvern", "Doomfang Wolf",
    "Dreadmaw Alligator", "Eldritch Horror", "Emberfang Direwolf", "Frostfang Polar Bear", "Ghastly Wraith",
    "Gorehorn Bison", "Grimclaw Sabertooth", "Hellfire Demon", "Ironjaw Warthog", "Lurking Abomination",
    "Mireclaw Lobster", "Netherfiend Imp", "Nightmare Phantom", "Oblivion Specter", "Plaguefiend",
    "Ravenshadow Crow", "Rotfiend Ghoul", "Scorchwing Wyvern", "Shadowclaw Jaguar", "Soulflame Ghost",
    "Thunderhoof Elk", "Venomfang Tarantula", "Vileblood Vampire", "Wailing Wraith", "Wight Revenant",
    "Zephyr Falcon", "Abyssal Kraken", "Aetherial Specter", "Ancient Titan", "Ashen Wyvern",
    "Blighted Dryad", "Bloodthorn Thornback", "Brimstone Titan", "Cinderclaw Cougar", "Corrupted Colossus",
    "Cursed Wraith", "Darksoul Specter", "Deathclaw Drake", "Doomfang Direwolf", "Dreadmaw Croc",
    "Eldritch Specter", "Emberfang Wolf", "Frostfang Grizzly", "Ghastly Phantom", "Gorehorn Buffalo",
    "Grimclaw Tiger", "Hellfire Fiend", "Ironjaw Boar", "Lurking Specter", "Mireclaw Crayfish",
    "Netherfiend Demon", "Nightmare Wraith", "Oblivion Phantom", "Plaguefiend Zombie", "Ravenshadow Raven",
    "Rotfiend Skeleton", "Scorchwing Drake", "Shadowclaw Panther", "Soulflame Wisp", "Thunderhoof Moose",
    "Venomfang Widow", "Vileblood Bat", "Wailing Specter", "Wightlord", "Zephyr Hawk"
];
